language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository

cache:
  directories:
    - $HOME/.gradle/caches/3.1
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon/3.1
    - $HOME/.gradle/wrapper/

script:
   - ./gradlew assembleDebug

deploy:
  provider: testfairy
  api-key: "7510ca0b488ac2d21e63a02a530a1b610e26cb9e"
#  app-file: ./app/build/outputs/apk/app-debug.apk
#  alias: android
#  testers-groups: qa-stuff
#  auto-update: true
#  data-only-wifi: true
#  metrics: cpu,memory,logcat,battery