language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository

cache:
  directories:
    - $HOME/.gradle/caches/3.1
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon/3.1
    - $HOME/.gradle/wrapper/

script:
   - ./gradlew assembleDebug